### ISSUE TITLE
After restarting chrome all rules are defect

### ISSUE THREAD

**Issue by pauschuu** [hultqvist/negotiator#29]
I installed the plugin. 

Activated chrome sync.

Created A LOT of rules.

Closed Chrome. Started Chrome again.

Then this:
![screenshot](https://cloud.githubusercontent.com/assets/12713838/9863828/ed6762e0-5b43-11e5-8266-6727ad149c74.png)

**Comment by hultqvist** [comment]
Before you try any fixes below please report on the following.

1. Which version are you using, the chrome web store(black button with a colored arrow, called "KISS Privacy") or the one from silentorbit.com, now called(Negotiator)? The latter one is newer and once I found it stable I will push it to the chrome webstore as an update to the extisting.

2. If you clear the errors and browse those websites again to the errors reappear?

3. Open the options page, do you have any actions listed?

4. Before you restarted the browser did the extension work as expected?

Once you have done this you can go to the options page and add the three actions manually. Or import the following set:

1. Backup!, Export and save.

If you are using the one from the chrome web store import this

	{
	"action:pass": {
		"block": "false",
		"color": "#4f4"
	},
	"action:clear": {
		"accept": "pass",
		"acceptcharset": "pass",
		"acceptencoding": "pass",
		"acceptlanguage": "pass",
		"agent": "pass",
		"block": "false",
		"color": "#8ce",
		"cookie": "remove",
		"referer": "remove"
	},
	"action:block": {
		"block": "true",
		"color": "#f64"
	}
	}

If you are running the "Negotiator" import this

	{
	"action:pass": {
		"color": "#4f4",
		"block": "false",
		"request": {},
		"response": {}
	},
	"action:clear": {
		"color": "#8ce",
		"block": "false",
		"request": {
			"referer": "remove",
			"cookie": "remove"
		},
		"response": {
			"set-cookie": "remove"
		}
	},
	"action:block": {
		"color": "#f64",
		"block": "true",
		"request": {},
		"response": {}
	}
	}
